services:
  db:
    image: mysql:8.0
    container_name: student-db
    environment:
      MYSQL_DATABASE: student_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: student-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root